# Generated by Django 4.2.7 on 2023-11-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='rating_user',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='rating_comment',
            new_name='rating',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('SP', 'спорт'), ('PO', 'политика'), ('HE', 'здоровье'), ('CA', 'автомобили')], max_length=2, unique=True),
        ),
    ]
